language: python
python:
  - 2.7
install:
  - virtualenv .
  - mkdir -p buildout-cache/{eggs,downloads}
  - bin/pip install --no-deps -e git+https://github.com/repodono/repodono.registry.git#egg=repodono.registry
  - bin/pip install --no-deps -e git+https://github.com/repodono/repodono.storage.git#egg=repodono.storage
  - bin/pip install zc.buildout
  - bin/buildout -Nc travis.cfg
script:
  - bin/code-analysis
  - bin/coverage run --source=src bin/test
after_success:
  - pip install -q coveralls==0.5
  - coveralls

notifications:
  email:
    - tommy.yu@auckland.ac.nz
